# Example of FoxService deployment. The operator will receive this specification and will create a deployment of two "fox-service" pods.
apiVersion: cbopt.com/v1
kind: FoxService # Identifier of the resource type.
metadata:
  name: test-fox # Name of the "FoxService" custom resource instance, may be changed to your liking
  namespace: default # Namespace must exist and account in KUBECONFIG must have sufficient permissions
spec:
  name: test-fox
  replicas: 2 # Number of "FoxService" pods created.
  containers:
    - name: test-fox
      image: inanimate/echo-server:latest
